### ISSUE TITLE
moving readme to mkdocs

### ISSUE THREAD

**Issue by sabuhish** [sabuhish/fastapi-mail#23]
implementation of  mkdocs for documentation

**Comment by maestro-1** [comment]
I believe a general improvement to the setup of the project would be really nice along with the addition of mkdocs. 
Like a linter, so that all committed code can have look uniform. And perhaps the addition of requirements.txt so that contributors can simple install the dependencies for the library with a simple _pip install_ command.

**Comment by sabuhish** [comment]
yes definitely I am going to do that as well, it is missing. It may take time but for sure will implement documentation with mkdocs. 
you are right thanks for reminding, I will add this now in order to help them contribute
