### ISSUE TITLE
Allow creating custom headers for attachments

### ISSUE THREAD

**Issue by wjurkowlaniec** [sabuhish/fastapi-mail#92]
Use case - attaching html images with Content-ID header to reference them in HTML content of email based on [RFC2392](https://datatracker.ietf.org/doc/html/rfc2392)

How to do it:
- Modify MessageSchema to allow setting custom headers, like this
```python

message = MessageSchema(
        subject=subject,
        recipients=recipients,
        html=html,
        subtype="html",
        attachments=[{"file": "/path/to/file", "headers":{"Content-ID": "<image1>"}, "mime_type" : "image", "mime_subtype": "png"}]
    )
```
`file` parameter can be as now, UploadFile and path

As it's hard to automagically import mime class  as they dont' have the same API, it's possible to do it through MIMEBase

So it's possible to add custom headers and override `mime_type` used in `MIMEBase` with `type` and `subtype` attributes

and in `MailMsg`, in `attach_file` method, unpack the structure and add headers.

I can code it if this is fine @sabuhish

**Comment by ramiswailem** [comment]
What about 'Content-Disposition', 'inline'? instead of fixed  value 'attachment'

[[ part.add_header('Content-Disposition', 'attachment', filename=filename)](https://github.com/sabuhish/fastapi-mail/blob/a95697251dd26804bc8ff3fe3e426a7f5723cf6a/fastapi_mail/msg.py#L66)](https://github.com/sabuhish/fastapi-mail/blob/a95697251dd26804bc8ff3fe3e426a7f5723cf6a/fastapi_mail/msg.py#L66)
